eastgenomics/eggd_generate_variant_workbook

- dxapp.json
- resources/home/dnanexus/vcf2xls_nirvana.pl
- src/vcf2xls_nirvana.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/6)
> Add version workflow + flagstat reads numbers

- Readme.developer.md
- dxapp.json
- resources/home/dnanexus/get_transcript_regions.py
- resources/home/dnanexus/vcf2xls_nirvana.pl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/11)
> Issues from code review

- resources/home/dnanexus/vcf2xls_nirvana.pl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/12)
> add normalization in the expected coverage

- resources/home/dnanexus/get_transcript_regions.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/14)
> integers for region coordinates + get exact regions instead of overlap

- resources/home/dnanexus/vcf2xls_nirvana.pl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/15)
> remove 5 bp flank addition

- resources/home/dnanexus/get_transcript_regions.py
- resources/home/dnanexus/vcf2xls_nirvana.pl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/16)
> 1 based exons for the scientists + get unique regions from coverage file

- dxapp.json
- resources/home/dnanexus/vcf2xls_nirvana.pl
Updated:
- Suggestions for dynamic files
- Version number
Fixed:
- Check if sample is in manifest
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/18)
> Fix empty xls

- src/vcf2xls_nirvana.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/7)
> Add unique output name

- resources/home/dnanexus/vcf2xls_nirvana.pl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/29)
> Re-organised report summary text to be DRYer

- dxapp.json
Didn't actually test it but it should work
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/34)
> changed timeout from 2 to 6

- dxapp.json
- src/vcf2xls_nirvana.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/36)
> Workflow id optional

- Readme.md
- dxapp.json
- src/vcf2xls_nirvana.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/63)
> check if raw vcf has a job id + minor changes in json help and readme

- dxapp.json
- resources/home/dnanexus/generate_workbook/generate_workbook.py
- resources/home/dnanexus/generate_workbook/utils/excel.py
- resources/home/dnanexus/generate_workbook/utils/filters.py
- resources/home/dnanexus/generate_workbook/utils/vcf.py
- src/code.sh
- use `bcftools isec` to identify excluded variants to write to xlsx
- improvements to summary sheet formatting
- fix issue in app code for getting job/workflow IDs to record
- fix fun bug with issues using quotes in app for passing in filter strings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_vcf2xls_nirvana/65)
> bug fixes, improvements

- resources/home/dnanexus/generate_workbook/tests/test_filters.py
- resources/home/dnanexus/generate_workbook/utils/excel.py
- Adds optional argument to output an empty 'comment' column appended to the end of variant sheets
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_workbook/69)
> Add optional comment column

- resources/home/dnanexus/generate_workbook/utils/excel.py
- resources/home/dnanexus/generate_workbook/utils/vcf.py
- Handle differing gnomAD fields for generating hyperlinks
- Improve setting column widths for non-specified fields
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_workbook/70)
> Minor fixes

- src/code.sh
- check on correct variable to add workflow id / name to Dias summary sheet when run as part of a workflow
- job: https://platform.dnanexus.com/projects/G9Q2B8843VxFBb9Y4j3PJ0g6/monitor/analysis/G9f03vQ43Vx8bVX35BPZPXqx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_workbook/74)
> Fix for correctly adding workflow id/name to summary

- Readme.md
- resources/home/dnanexus/generate_workbook/utils/vcf.py
- Fixes incorrect mastermind values by building alt specific URL
- Update readme to detail URLs used
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_workbook/77)
> Fix URL bug

- src/code.sh
- explicitly check if boolean inputs are passed to correctly evaluate, if not and there is a default they always evaluate to true
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_workbook/82)
> fix evaluating boolean inputs

- dxapp.json
- resources/home/dnanexus/generate_workbook/utils/vcf.py
Successful job: https://platform.dnanexus.com/projects/G9Q2B8843VxFBb9Y4j3PJ0g6/monitor/job/GB3fYBj43VxG6ZzZ4KqXJ76q
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_workbook/83)
> VW-122 - bug fix for correctly casting CHROM values to str type

- dxapp.json
- resources/home/dnanexus/generate_workbook/utils/excel.py
- Fix bug in 2 missing rows in ACMG report template
- Example job: https://platform.dnanexus.com/projects/G9Q2B8843VxFBb9Y4j3PJ0g6/monitor/job/GB7bZx843Vx5Gz37Fpb8gQ2y
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_workbook/87)
> VW-124 Fix report template

- resources/home/dnanexus/generate_workbook/utils/excel.py
Minor formatting changes and adjustments
- Colour BA1 cell in ACMG sheet - fixes #90 
- Merge more right cells to panel and CI in summary sheet - fixes #89 
- Adjustment of column widths for HGMD rankscore and gnomAD columns - closes #88 
- wider HGMD to not trim title and narrower gnomAD
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_workbook/102)
> Padding and adjustments

- dxapp.json
- resources/home/dnanexus/generate_workbook/utils/excel.py
Freezes header of variant sheets for nicer scrolling of many variants
Closes #99
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_workbook/101)
> Freeze header

- resources/home/dnanexus/generate_workbook/utils/excel.py
reverted to match current main branch: https://github.com/eastgenomics/eggd_generate_workbook/blob/5ea955923f8362d2ccfdabdd782ce4917d89a653/resources/home/dnanexus/generate_workbook/utils/excel.py#L518-L532
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_workbook/109)
> revert sorting null values

- dxapp.json
- resources/home/dnanexus/generate_workbook/tests/test_utils.py
- resources/home/dnanexus/generate_workbook/utils/excel.py
- resources/home/dnanexus/generate_workbook/utils/utils.py
- resources/home/dnanexus/generate_workbook/utils/vcf.py
Properly check for if a cell value is numeric when building the hyperlink to store it with the appropriate type
Closes #111
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/112)
> Fix url value typing

- resources/home/dnanexus/generate_workbook/tests/test_utils.py
- resources/home/dnanexus/generate_workbook/utils/utils.py
+ more test values
```
$ python3 -m pytest -v resources/home/dnanexus/generate_workbook/tests/test_utils.py 
=================================================== test session starts ====================================================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/jethro/Projects/eggd_vcf2xls_nirvana/resources/home/dnanexus/generate_workbook/tests, configfile: pytest.ini
collected 1 item                                                                                                           
resources/home/dnanexus/generate_workbook/tests/test_utils.py::test_is_numeric PASSED                                [100%]
==================================================== 1 passed in 0.02s …
```
> better specificity of utils.is_numeric()

- Readme.md
Fixes #115
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/118)
> Fix readme typo

- resources/home/dnanexus/generate_workbook/utils/excel.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/119)
> Fix typo on setting max column width for additional files

- resources/home/dnanexus/generate_workbook/utils/excel.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/129)
> add colouring summary to dias summary

- Readme.md
Fixes #124
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/131)
> add decipher URL to readme

- resources/home/dnanexus/generate_workbook/utils/excel.py
- src/code.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/132)
> fix summary sheet ID parsing

- dxapp.json
- requirements.txt
- resources/home/dnanexus/generate_workbook/tests/test_columns.py
- resources/home/dnanexus/generate_workbook/tests/test_vcf.py
- resources/home/dnanexus/generate_workbook/utils/columns.py
- resources/home/dnanexus/generate_workbook/utils/vcf.py
- Added handling for VEP fields with duplicates due to multiple transcripts.
- Added hyperlinks for COSMIC field.
Screenshot:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/134)
> Cosmic handling

- Readme.md
- dxapp.json
- resources/home/dnanexus/generate_workbook/generate_workbook.py
- resources/home/dnanexus/generate_workbook/utils/excel.py
- src/code.sh
Add in optional `-ifreeze_columns` argument for being able to fix row / columns on scrolling
Ticket context: https://cuhbioinformatics.atlassian.net/jira/servicedesk/projects/EBH/queues/custom/14/EBH-1728
Closes #135 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/136)
> Configurable column freezing

- Readme.md
- dxapp.json
- resources/home/dnanexus/generate_workbook/generate_workbook.py
- resources/home/dnanexus/generate_workbook/tests/test_utils.py
- resources/home/dnanexus/generate_workbook/utils/excel.py
- resources/home/dnanexus/generate_workbook/utils/utils.py
- resources/home/dnanexus/generate_workbook/utils/vcf.py
- src/code.sh
Handle adding of additional hyperlinks to external resources not from standard VEP annotation in the VCF, now will handle decipher, oncoKB, PeCan and cBioPortal.
- New input `--additional_columns` , list of strings of columns to add
- `map_chr_to_nc()` moved from `vcf.py` to `utils.py` (no changes to function)
- new class `buildHyperlink()`, contains all logic for generating hyperlinks (moved and extended from `vcf.make_hyperlinks()`)
Test job: https://platform.dnanexus.com/projects/GX1K52Q4KK64pp0x709gj2Qy/monitor/job/GXJF8884KK6F9zKQpp111Fbz
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/142)
> Additional TSO links

- Readme.md
- dxapp.json
- resources/home/dnanexus/generate_workbook/generate_workbook.py
- resources/home/dnanexus/generate_workbook/utils/vcf.py
- src/code.sh
Boolean option to add additional empty column for recording classification like is done for comments column
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/146)
> Add classification column

- dxapp.json
- resources/home/dnanexus/generate_workbook/generate_workbook.py
- resources/home/dnanexus/generate_workbook/tests/test_vcf.py
- resources/home/dnanexus/generate_workbook/utils/excel.py
- resources/home/dnanexus/generate_workbook/utils/vcf.py
- src/code.sh
Add another optional input for adding a simple concat column of chrom, pos, ref and alt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/149)
> Add yet another column to make Jon happy pt. 3

- Readme.md
- resources/home/dnanexus/generate_workbook/utils/excel.py
Improvements to change basic summary sheet to one specific for Helios and some adjustments to column formatting
Summary sheet changes:
- adds parsing of specific metrics from additional sheet if MetricsOutput is passed with colouring similar to what is done in `excel.colour_metrics_output()`
- parses in TMB, MSI and Gene amplifications if passed
Column formatting:
- set displaying of VF to 2dp
- lots of width adjustments
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/150)
> Improvements to summary sheet and formatting

- resources/home/dnanexus/generate_workbook/utils/excel.py
- resources/home/dnanexus/generate_workbook/utils/vcf.py
Adding dropdowns function to the workbook.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/160)
> Function for downdowns

- resources/home/dnanexus/generate_workbook/utils/excel.py
Changes: 
- added `STRENGTH` and `POINTS` in col I and L (for free text)
- added `Total Points` merged cell at row 25, col G
- removed row containing `PP4` and `BP6`
- updated the wording in col B as Kate suggested
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/162)
> updating_report_table

- Readme.md
- dxapp.json
- resources/home/dnanexus/generate_workbook/generate_workbook.py
- resources/home/dnanexus/generate_workbook/utils/excel.py
- src/code.sh
Changes:
- excel.py - added locking function for all sheets
- update reame and dxapp.json files to include the command line arguments
- update code.sh to add new arguments
- update generate_workbook.py to add args
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/163)
> adding_locking_function

- resources/home/dnanexus/generate_workbook/utils/excel.py
Changes:
- removed GEM table in summary sheet as Isabelle requested
- formatting color, font and table structure in report table  as requested
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/164)
> modify summary and report tables

- resources/home/dnanexus/generate_workbook/utils/excel.py
- added a function to prevent renaming sheet
- minor adjustments for font size and col width
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/165)
> added function to prevent sheet renaming

- resources/home/dnanexus/generate_workbook/utils/excel.py
Changes:
- remove "ACMG classification" row in report table as there is a drop-down row for that - requested by Isabelle.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/166)
> remove classification row in report table

- resources/home/dnanexus/generate_workbook/utils/excel.py
Changes:
- added one extra item (Stand-Alone) for BA1 drop-down
- refactor the drop-down function to avoid repeating scripts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/168)
> update dropdown function

- resources/home/dnanexus/generate_workbook/utils/excel.py
added if statement so that the drop-downs are added only when there is variant(s) in "included/variant" sheet.
added if statement so that locking sheet name function is called only when `--lock_sheet` args is true
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/170)
> add if statement for num_variant

- dxapp.json
change default value of acmg from 3 to 0 so that newly added functions are called only if acmg is not 0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/171)
> change defatult acmg num

- resources/home/dnanexus/generate_workbook/utils/excel.py
Changes:
- Increase unlocked row from 200 to 500 in all sheets
- update the PID box in the summary sheet
- swap between BA1 and BS1 rows in interpret sheets
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/174)
> update summary and interpret sheets

- resources/home/dnanexus/generate_workbook/utils/excel.py
Added a few lines in "lock_sheet" function to allow scientists to highlight rows/cols and adjust the col width/row height. 
This feature is working only in windows MS (not in Libre in Linux)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/180)
> update lock_sheet function

- resources/home/dnanexus/generate_workbook/generate_workbook.py
- resources/home/dnanexus/generate_workbook/utils/excel.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/181)
> IN-502 make a uranus summary sheet

- Readme.md
- dxapp.json
- resources/home/dnanexus/generate_workbook/generate_workbook.py
- resources/home/dnanexus/generate_workbook/tests/test_vcf.py
- resources/home/dnanexus/generate_workbook/utils/excel.py
- resources/home/dnanexus/generate_workbook/utils/vcf.py
- src/code.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/183)
> IN-503 Option to have AF presented as a decimal or percentage

- resources/home/dnanexus/generate_workbook/utils/excel.py
Updates:
- change some title names
- reformatting tables
- add a new 'MLPA confirmation' table
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/186)
> update summary page

- resources/home/dnanexus/generate_workbook/utils/excel.py
Update start column for unlock in summary sheet as the size of tables now changed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/187)
> update start col for unlock

- Readme.md
- resources/home/dnanexus/generate_workbook/utils/utils.py
New link example: https://pecan.stjude.cloud/variants/proteinpaint/?gene=BRCA1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/191)
> IN-534 pecan link needs updating

- src/code.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/195)
> IN-500 syntax fix

- resources/home/dnanexus/generate_workbook/utils/vcf.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/199)
> IN-500 use dna or protein change if provided

- resources/home/dnanexus/generate_workbook/tests/test_vcf.py
- resources/home/dnanexus/generate_workbook/utils/vcf.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/200)
> In 500 make additional sheet consistent with main vcf

- resources/home/dnanexus/generate_workbook/generate_workbook.py
- resources/home/dnanexus/generate_workbook/tests/test_vcf.py
- resources/home/dnanexus/generate_workbook/utils/vcf.py
- src/code.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_generate_variant_workbook/202)
> URA-899 request to change prev count ac to be formatted as prev count ac an
